### ISSUE TITLE
cannot find package "github.com/brutella/hc"

### ISSUE THREAD

**Issue by lukeghayes** [brutella/hklifx#17]
I managed to get this setup up on my raspberry pi. 

All was working well but later that day the lights became unreachable and terminal said

`~/GO_WORKSPACE/src/hklifx $ go run hklifxd.go -pin 00102003 -v
hklifxd.go:9:2: cannot find package "github.com/brutella/hc" in any of:
    /usr/local/go/src/github.com/brutella/hc (from $GOROOT)
    ($GOPATH not set)
`

I couldn't get it to start again so I deleted all the files from my computer and setup again and it worked.

That was until this morning when I cannot connect again and am getting the same message.

Can anyone help me? im a bit of a newb so the more info the better.

**Comment by brutella** [comment]
The compiler looks for the `github.com/brutella/hc` package in the `$GOROOT` directory (because you haven't define `$GOPATH` direct). In your case the `$GOROOT` environment variable is set to `/usr/local/go/src/`. But there is no folder at `/usr/local/go/src/github.com/brutella/hc`.

You should define `$GOPATH` to point to `~/GO_WORKSPACE` as described [here](https://golang.org/doc/code.html#Organization) and make sure that there are files in `~/GO_WORKSPACE/src/github.com/brutella/hc`
